# Generated by Django 3.0.1 on 2020-01-13 20:01
from os import listdir
from os.path import isfile, join

from django.db import migrations
from django.conf import settings

import pandas as pd


def fill_table_SB(apps, schema_editor):
    """Fill SB Config Tables"""
    sb_config_path = join(settings.BASE_DIR, 'vol', 'sb_config')
    sb_files = [f for f in listdir(
        sb_config_path) if isfile(join(sb_config_path, f))]
    sb_files = pd.DataFrame(sb_files, columns=['File'])
    sb_files[['Name', 'Extention']] = sb_files.File.str.split(
        '.', n=1, expand=True)

    # SB03
    SB03 = apps.get_model('core', 'SB03')
    df = pd.read_csv(sb_config_path + 'SB03.txt',
                     sep='~',
                     low_memory=False,
                     encoding='latin',)
    row_iter = df.iterrows()

    objs = [

        SB03()

        for index, row in row_iter

    ]

    SB03.objects.bulk_create(objs)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_table_SB),
    ]
