# Generated by Django 3.0.2 on 2020-01-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_sb_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='resource_name',
            field=models.CharField(choices=[('AH', 'Account History'), ('AT04CRE', 'AT04 CRE'), ('AT07', 'AT07'), ('BBAT', 'Bal By Acct Transformada'), ('CND', 'Cartera No Dirigida'), ('CD', 'Cartera Dirigida'), ('FDN', 'Fecha de Nacimiento'), ('GICG', 'Gavetas ICG'), ('LNP860', 'LNP860'), ('MM', 'Migrate Mortgage'), ('MISP', 'MIS Provisiones'), ('PPRRHH', 'Prestamos sobre Prestaciones RRHH'), ('RICG', 'Rendimientos ICG'), ('SIIF', 'SIIF'), ('SC', 'Sobregiros Consumer'), ('VNP003T', 'VNP003T')], default='', max_length=50),
        ),
    ]
