# Generated by Django 3.0.1 on 2020-01-13 20:01
from os import listdir
from os.path import isfile, join

from django.db import migrations
from django.conf import settings

import pandas as pd


def fill_table_sb(apps, schema_editor):
    """Fill SB Config Tables"""
    sb_config_path = join(settings.BASE_DIR, 'vol', 'sb_config')
    sb_files = [f for f in listdir(
        sb_config_path) if isfile(join(sb_config_path, f))]
    sb_files = pd.DataFrame(sb_files, columns=['File'])
    sb_files[['Name', 'Extention']] = sb_files.File.str.split(
        '.', n=1, expand=True)
    files_row_iter = sb_files.iterrows()

    for i, r in files_row_iter:
        objs = []

        if r['Extention'] == 'txt':
            SB = apps.get_model('core', r['Name'])
            df = pd.read_csv(join(sb_config_path, r['File']),
                             sep='~',
                             low_memory=False,
                             encoding='utf-8-sig',)
            row_iter = df.iterrows()

            if r['Name'] == 'SB03':
                objs = [
                    SB(
                        Codigo_Pais=row['Codigo_Pais'],
                        Nombre_Pais=row['Nombre_Pais']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB09':
                objs = [
                    SB(
                        Tipo_Credito=row['Tipo_Credito'],
                        Nombre_Tipo_Credito=row['Nombre_Tipo_Credito']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB10':
                objs = [
                    SB(
                        Actividad_Economica=row['Actividad_Economica'],
                        Nombre_Actividad=row['Nombre_Actividad']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB11':
                objs = [
                    SB(
                        Garantia=row['Garantia'],
                        NombreGarantia=row['NombreGarantia'],
                        Descripcion=row['Descripcion']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB15':
                objs = [
                    SB(
                        Moneda=row['Moneda'],
                        Nombre_Moneda=row['Nombre_Moneda'],
                        Pais=row['Pais'],
                        Moneda_Secore=row['Moneda_Secore'],
                        Moneda_RDWH=row['Moneda_RDWH'],
                        Moneda_UltraSec=row['Moneda_UltraSec']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB16':
                objs = [
                    SB(
                        Codigo_Tipo_Persona=row['Codigo_Tipo_Persona'],
                        Nombre_Tipo_Persona=row['Nombre_Tipo_Persona']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB19':
                objs = [
                    SB(
                        Clasificacion_Riesgo=row['Clasificacion_Riesgo'],
                        NombreClasificacion_Riesgo=row['NombreClasificacion_Riesgo']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB30':
                objs = [
                    SB(
                        Periodicidad=row['Periodicidad'],
                        Nombre_Periodicidad=row['Nombre_Periodicidad']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB31':
                objs = [
                    SB(
                        Codigo_Indicador=row['Codigo_Indicador'],
                        Descripcion_Codigo_Indicador=row['Descripcion_Codigo_Indicador']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB34':
                objs = [
                    SB(
                        Codigo_Estado_Credito=row['Codigo_Estado_Credito'],
                        Nombre_Estado_Credito=row['Nombre_Estado_Credito']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB35':
                objs = [
                    SB(
                        Codigo_Situacion_Credito=row['Codigo_Situacion_Credito'],
                        Nombre_Situacion_Credito=row['Nombre_Situacion_Credito']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB59':
                objs = [
                    SB(
                        Genero=row['Genero'],
                        Descripcion_Genero=row['Descripcion_Genero']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB66':
                objs = [
                    SB(
                        Codigo_Uso=row['Codigo_Uso'],
                        Descripcion_Codigo_Uso=row['Descripcion_Codigo_Uso']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB67':
                objs = [
                    SB(
                        Codigo_Medida=row['Codigo_Medida'],
                        Unidad_Medida=row['Unidad_Medida']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB68':
                objs = [
                    SB(
                        Codigo_Plazo=row['Codigo_Plazo'],
                        Nombre_Plazo=row['Nombre_Plazo']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB76':
                objs = [
                    SB(
                        Codigo_Naturaleza=row['Codigo_Naturaleza'],
                        Descripcion_Naturaleza=row['Descripcion_Naturaleza']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB81':
                objs = [
                    SB(
                        Codigo_Modalidad=row['Codigo_Modalidad'],
                        Descripcion_Modalidad=row['Descripcion_Modalidad']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB82':
                objs = [
                    SB(
                        Codigo_Uso_Financiero=row['Codigo_Uso_Financiero'],
                        Uso_Financiero=row['Uso_Financiero']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB83':
                objs = [
                    SB(
                        Codigo_Destino=row['Codigo_Destino'],
                        Descripcion_Destino=row['Descripcion_Destino']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB85':
                objs = [
                    SB(
                        Tipo_Proyecto=row['Tipo_Proyecto'],
                        Descripcion_Tipo_Proyecto=row['Descripcion_Tipo_Proyecto']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB87':
                objs = [
                    SB(
                        Codigo_Sector=row['Codigo_Sector'],
                        Descripcion_Sector=row['Descripcion_Sector']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB87':
                objs = [
                    SB(
                        Codigo_Sector=row['Codigo_Sector'],
                        Descripcion_Sector=row['Descripcion_Sector']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB88':
                objs = [
                    SB(
                        Codigo_Rubro=row['Codigo_Rubro'],
                        Clasificacion=row['Clasificacion']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB90':
                objs = [
                    SB(
                        Codigo_Modalidad=row['Codigo_Modalidad'],
                        Descripcon_Modalidad=row['Descripcon_Modalidad']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB92':
                objs = [
                    SB(
                        Codigo_Destino=row['Codigo_Destino'],
                        Descripcion_Destino=row['Descripcion_Destino']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB100':
                objs = [
                    SB(
                        Tipo_Operaciones=row['Tipo_Operaciones'],
                        Descripcion_Tipo_Operaciones=row['Descripcion_Tipo_Operaciones']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB101':
                objs = [
                    SB(
                        Codigo_Segmento=row['Codigo_Segmento'],
                        Descripcion_Segmento=row['Descripcion_Segmento']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB102':
                objs = [
                    SB(
                        Codigo_Zona=row['Codigo_Zona'],
                        Descripcion_Zona=row['Descripcion_Zona']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB103':
                objs = [
                    SB(
                        Tipo_Subsector=row['Tipo_Subsector'],
                        Descripcion_Tipo_Subsector=row['Descripcion_Tipo_Subsector']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB105':
                objs = [
                    SB(
                        Codigo_Destino=row['Codigo_Destino'],
                        Descripcion_Destino=row['Descripcion_Destino']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB136':
                objs = [
                    SB(
                        Codigo_Tipo_Industria=row['Codigo_Tipo_Industria'],
                        Descripcion_Tipo_Industria=row['Descripcion_Tipo_Industria'],
                        Definicion_Tipo_Industria=row['Definicion_Tipo_Industria']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB137':
                objs = [
                    SB(
                        Codigo_Tipo_Beneficiario=row['Codigo_Tipo_Beneficiario'],
                        Descripcion_Tipo_Beneficiaio=row['Descripcion_Tipo_Beneficiaio'],
                        Definicion_Tipo_Beneficiario=row['Definicion_Tipo_Beneficiario']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB138':
                objs = [
                    SB(
                        Codigo_Tipo_Vivienda=row['Codigo_Tipo_Vivienda'],
                        Nombre_Tipo_Vivienda=row['Nombre_Tipo_Vivienda']
                    )
                    for index, row in row_iter
                ]
            elif r['Name'] == 'SB140':
                objs = [
                    SB(
                        Codigo_Tipo_Beneficiario=row['Codigo_Tipo_Beneficiario'],
                        Descripcion_Tipo_Beneficiaio=row['Descripcion_Tipo_Beneficiaio'],
                        Definicion_Tipo_Beneficiario=row['Definicion_Tipo_Beneficiario']
                    )
                    for index, row in row_iter
                ]

            SB.objects.bulk_create(objs)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_table_sb),
    ]
